FROM node:22-alpine AS dev
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .

EXPOSE 4201
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4201", "--poll", "2000", "--configuration", "docker"]
